# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
exclude_unchanged = true
bin = "./tmp/push-relay"
cmd = "go build -o ./tmp/push-relay ./main.go"
full_bin = "dlv exec ./tmp/push-relay --listen=:4000 --headless=true --api-version=2 --accept-multiclient --continue --log"
include_ext = ["go"]
exclude_dir = [".vscode", ".github", "bin", "tmp", "pgdata", "dist", "githooks"]
exclude_regex = ["_test.go"]

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
