services:
  app:
    container_name: attom
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: air
    ports:
      - "4000:4000"
      - "8181:8080"
    environment:
      - GO111MODULE=on
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:9.6.13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esus
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
